-- =============================================================================
-- gen_fivem_server_stubs.lua
-- =============================================================================
-- Extract server native registrations from a local FiveM source tree and emit
-- fallback Lua globals for CfxLua standalone runtime.
--
-- Usage:
--   lua tools/gen_fivem_server_stubs.lua [fivem-root]
--
-- Output:
--   Writes Lua code to stdout.
-- =============================================================================

local fivemRoot = arg[1] or "fivem"

local function run(cmd)
    local p = io.popen(cmd, "r")
    if not p then
        io.stderr:write("[gen_fivem_server_stubs] failed to run command: " .. cmd .. "\n")
        os.exit(1)
    end

    local out = {}
    for line in p:lines() do
        out[#out + 1] = line
    end

    local ok = p:close()
    if ok == nil then
        io.stderr:write("[gen_fivem_server_stubs] command failed: " .. cmd .. "\n")
        os.exit(1)
    end

    return out
end

local function toPascal(upperSnake)
    local parts = {}
    for part in upperSnake:gmatch("[^_]+") do
        parts[#parts + 1] = part:sub(1, 1):upper() .. part:sub(2):lower()
    end
    return table.concat(parts)
end

local rgCmd = string.format(
    "rg -No --no-filename 'RegisterNativeHandler\\(\\\"([A-Z0-9_]+)\\\"' " ..
    "%s/code/components/citizen-server-impl/src %s/code/components/scripting-server/src -r '$1'",
    fivemRoot, fivemRoot
)

local registered = {}
for _, native in ipairs(run(rgCmd)) do
    registered[native] = true
end

local names = {}
for upperSnake in pairs(registered) do
    names[#names + 1] = toPascal(upperSnake)
end

table.sort(names)

if #names == 0 then
    io.stderr:write("[gen_fivem_server_stubs] no server native registrations found under: " .. fivemRoot .. "\n")
    os.exit(1)
end

io.write("-- AUTO-GENERATED by tools/gen_fivem_server_stubs.lua -- DO NOT EDIT\n")
io.write("-- Source: local FiveM C++ server registrations (RegisterNativeHandler)\n")
io.write("-- Generated for standalone server-side API surface parity (name coverage).\n\n")

io.write("local function __cfx_stub_nil() return nil end\n\n")

for _, name in ipairs(names) do
    io.write(string.format("_G['%s'] = _G['%s'] or __cfx_stub_nil\n", name, name))
end

io.write("\n")
io.write("-- End of generated server native fallback stubs\n")
